### ISSUE TITLE
License/copying terms missing for this repository

### ISSUE THREAD

**Issue by mhucka** [t-b/git-pre-commit-hook-windows-filenames#2]
I realize this is a very old repository, but it provides a very useful program that I have not found elsewhere.  (Thank you for creating it!)  I would like to use it in other projects; however, this repository currently only gives a copyright – it mentions no terms of use or redistribution. If at all possible, it would be very helpful to add a license so that people who come across this repository can know what they can or can't do. 

(Selfishly, I would like to recommend a nonviral license such as the Apache, MIT or BSD licenses, so that forks of this script can be placed in repositories that use those software licenses. But, obviously, the decision is up to the author.)

**Comment by t-b** [comment]
Thanks for the issue. That is indeed a problem. I never expected this toy repo to gain any attraction.

I've opened #3 to add a License. Would that work for you?

**Comment by mhucka** [comment]
Hi – thank you for responding so incredibly quickly. The license proposed in #3 would work great as far as I'm concerned. It looks like a BSD 3-clause license, correct? I would only make the suggestion to explicitly state somewhere (maybe in the readme?) that the software uses a BSD 3-clause license, so that people can recognize it more quickly. I don't mean something complicated, just something along the lines of "this software is distributed under the terms of a BSD 3-clause software license" somewhere, that sort of thing. (But this is optional, and if you don't have time or simply don't want to, that'd be fine too, of course.)

**Comment by t-b** [comment]
@mhucka Good point, I've added my usual header in the files.

Thanks for the report.
